spring:
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev #开发环境
  application:
    name: mscloud-config-dev
---
spring:
  profiles: testdev #測試环境
  application:
    name: mscloud-config-test
    
#使用UTF-8格式
          
