spring:
  profiles:
    active:
    - dev

---
server:
  port: 3355
spring:
   profiles: dev
   application:
    name: mscloud-dept-3355-dev 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      


---
server:
  port: 3355
spring:
   profiles: test
   application:
    name: mscloud-dept-test 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      


